version: '2'

services:
  rest:
    build: ./rest
    container_name: rest
    image: appdynamics/sample-app
    links:
      - db
    volumes:
      - .:/appdynamics
    ports: 
      - "8080:8080"

  db:
    container_name: db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=singcontroller  
    ports: 
      - "3306:3306"
